### ISSUE TITLE
ENAMETOOLONG for chapters with long title names

### ISSUE THREAD

**Issue by alecgibson** [cyrilis/epub-gen#52]
`epub-gen` fails to render an ePub with an arbitrarily long chapter title. This is because the chapter titles gets turned into a slug, and this slug exceeds the system's maximum for path length.

A simple fix for this would be to truncate titles to a shorter length. If this is done, it would be nice to feed back to the consumer what these slugs are (ie as the resolution of the `Promise`). This is especially useful when - for example - trying to construct your own custom table of contents.

**Comment by pedrosanta** [comment]
Hey @alecgibson, that totally makes sense, I'll put up a PR with it. 👍

**Comment by pedrosanta** [comment]
Hi @alecgibson, so I've been looking to the code and how it is, might be tricky to provide that on `Promise` resolution, because at that point the TOC is already generated – isn't ringing as optimal to me, idk.

How about an approach similar to:
- allow the lib users to provide their own optional slugs contents – as an option, we'll add and document that;
- but this way it was the lib user responsibility to truncate the slugs as they deem fit(1);

(1) I'm stating this one, because I'm thinking that each user/project will have their files/folders in different depths/path sizes on each system and path/filename sizes might *be dependent of each environment*, hence giving that option to lib users. IDK, does this make sense? 🤔

**Comment by alecgibson** [comment]
Yeah, didn't know we had that option! Makes sense. Happy to close this.
