### ISSUE TITLE
The process randomly stop when downloading lots of images

### ISSUE THREAD

**Issue by maple3142** [cyrilis/epub-gen#66]
The process randomly stop when downloading lots of images.
Reproduction steps:
1. git clone https://github.com/maple3142/dmzj-novel.git
2. npm i
3. node dl.js 2140 Goblin_Slayer.epub (This one works well)
4. node dl.js 1279 ngnl.epub (This one will stop working)

**Comment by cyrilis** [comment]
Hi @maple3142 

Sorry for late reply, this could happen when there are too many images to download. If this happens a lot, you can pre-download all the images referenced in these HTMLs into local disk.  then update the images `src` attribute to the file on local disk.

For example:  

```html
 <img src="http://asserts.com/images.png" />
```
Download image: `http://asserts.com/images.png` 
Into local file: `/usr/local/share/epub_tmp/413241.png`
Alter html image src attribute into: 

```html
 <img src="file:///usr/local/share/epub_tmp/413241.png" />
```

Then generate epub file with updated html string, so that `epub-gen` library will not download image while generating epub file.

**Comment by cyrilis** [comment]
Closing for now.  If you have any question, please reopen again.
